#ifndef namefix_idl
#define namefix_idl

#include <wpfsys.idl>

  interface M_WPFileSystemFix;
  interface WPFileSystemFix: WPFileSystem
  {
     attribute BOOL fIsInitialized;
#ifdef __SOMIDL__
      implementation
     {
        local;
        majorversion      = 1;
        minorversion      = 1;
        filestem          = filesys;
        dllname           = "filesys.dll";
        callstyle         = oidl;
        metaclass         = M_WPFileSystemFix; 
        classinit         = InitOnce;
        fIsInitialized    :staticdata;
        somDefaultInit    :override, init;
        somDestruct       :override;
        wpModifyMenu      :override;
        wpMenuItemSelected:override;
        wpInitData        :override;

        releaseorder      :fIsInitialized,_get_fIsInitialized,_set_fIsInitialized;

        passthru C_xh_before = ""
        "#define INCL_PM"
        "#define INCL_BASE"
        "#define INCL_DOSDEVIOCTL"
        "#include <os2.h>"
        "";

        passthru C_xih_after = ""
        "#ifdef __cplusplus"
        "   extern \"C\" {"
        "#endif"
        "int _CRT_init(void);"
        "void _CRT_term(void);"
        "void __ctordtorInit(void);"
        "void __ctordtorTerm(void);"
        "#ifdef __cplusplus"
        "}"
        "#endif"
        "#include <ctype.h>"
        "#include <rc.h>"
        "#include <wpfolder.xh>"
        "#include <wpdataf.xh>"
        "#include <lvm_intr.h>"
        "";
      };
#endif
  };      


   interface M_WPFileSystemFix: M_WPFileSystem
   {
#ifdef __SOMIDL__
      implementation 
     {
        local;
        majorversion = 1;
        minorversion = 1;
        callstyle    = oidl;
        filestem     = filesys;
        dllname      = "filesys.dll";
      };
#endif
   };

#endif

